# Generated by Django 4.1.3 on 2022-11-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partoapp', '0002_details_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parto_dets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_dilation', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
