# Generated by Django 4.1.3 on 2022-11-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partoapp', '0003_parto_dets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parto_dets',
            name='c_dilation',
            field=models.IntegerField(null=True),
        ),
    ]
