# Generated by Django 4.1.3 on 2022-11-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partoapp', '0004_alter_parto_dets_c_dilation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhr', models.IntegerField(null=True)),
                ('hrs', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='phone',
            field=models.BigIntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='parto_dets',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parto_dets',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
