# Generated by Django 4.1.3 on 2022-11-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partoapp', '0005_section1_details_phone_alter_details_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amnioticfluid', models.CharField(max_length=50)),
                ('moulding', models.CharField(max_length=50)),
                ('protein', models.CharField(max_length=50)),
                ('acetone', models.CharField(max_length=50)),
                ('volume', models.CharField(max_length=50)),
            ],
        ),
    ]
