# Generated by Django 4.1.3 on 2022-11-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partoapp', '0006_section2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractionsno', models.IntegerField(null=True)),
                ('contractionsdur', models.IntegerField(null=True)),
                ('chours', models.IntegerField(null=True)),
                ('oxytocin', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='section2',
            name='acetone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section2',
            name='amnioticfluid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section2',
            name='moulding',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section2',
            name='protein',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section2',
            name='volume',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
