# Generated by Django 4.1.3 on 2022-11-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Partoapp', '0007_section3_alter_section2_acetone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section3',
            name='contractionsdur',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='section3',
            name='contractionsno',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
